version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "ouestcharlie-py-toolkit"
      - dependency-name: "ouestcharlie-whitebeard"
      - dependency-name: "ouestcharlie-wally"
