name: Build ouestcharlie-woof

on:
  pull_request:
  push:
    tags: ["v*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Build gallery
        working-directory: gallery
        run: npm ci && npm run build

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install hatch
        run: pip install hatch

      - name: Build
        run: hatch build

      - uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist/
